### ISSUE TITLE
Support h264 profile and level encoding parameters

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/avpipe#61]
Add optional encoding parameters 'profile' and 'level'. 
These parameter are codec-specific so they need to be validated against h264 (or h265) codecs.
Preserve the current (automatic) behavior when profile and level are not specified.

**Comment by elv-reza** [comment]
Is this for mez making or for ABR segments?
Notice that the profile and level can be different for different encoders. For example, libx264 and h264_nvenc can have different profile and level for the same video.
